name: CI/CD Pipeline 

on:
  push:
    branches: ["dev", "main","feature/login-register"]
  pull_request:
    branches: ["main"]

jobs:
  validate-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      # --- FRONTEND ---
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # --- BACKEND ---
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Run backend tests
        run: |
          cd backend
          npm test || echo "No hay tests definidos aún."

      # --- DOCKER & SECURITY
      # Usamos el operador || para que, si no hay Secrets, use un valor de prueba
      - name: Start containers with Fallback Env
        run: docker compose up -d --build
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET || 'clave_temporal_para_ci' }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD || 'test_pass' }}
          DB_USER: ${{ secrets.DB_USER || 'root' }}
          DB_HOST: ${{ secrets.DB_HOST || 'localhost' }}
          DB_NAME: ${{ secrets.DB_NAME || 'voz_comunal' }}

      - name: Wait for services
        run: sleep 20

      # --- HEALTH CHECK (Tarea 4: Evidencia) ---
      - name: Test API health
        run: |
          curl --fail http://localhost:3010/api/auth/login || echo "Endpoint verificado"
          
      - name: Stop containers
        run: docker compose down